Set image name and proper name via flags

diff --git a/install b/install
--- a/install
+++ b/install
@@ -8,34 +8,37 @@
 set -euo pipefail
 IFS=$'\n\t'
 
-NAME="Debian 7 LX Brand"
 BUILD_DATE=$(date +%Y%m%d)
-TARGET="debian-7-lx-${BUILD_DATE}.tar.gz"
 
 usage() {
 cat <<EOF
 
-  Usage: $0 -d <chroot> -m <mirror> -u <image docs>
+  Usage: $0 -d <chroot> -m <mirror> -i <image name> -p <proper name> -u <image docs>
   
   Install and modify Debian in a given directory in a given directory using a given mirror
 
   Example:
-  $0 -d /data/chroot -m http://httpredir.debian.org/debian/ -u https://docs.joyent.com/images/lx-brand-beta
+  $0 -d /data/chroot -m http://httpredir.debian.org/debian/ -i lx-debian-7 -p "Debian 7 LX Brand" -u https://docs.joyent.com/images/lx-brand-beta
 
   OPTIONS:
   -d A path to the install directory
   -m A URL for the desired archive mirror
+  -i The name of the image. This is used for naming the tarball. 
+  -p The proper name of the image. Use quotes. This is used in the MOTD and /etc/product file. 
   -u A URL to the image docs [optional]
   -h Show this message
+
 
 EOF
 }
 
 INSTALL_DIR=
 MIRROR=
+IMAGE_NAME=
+NAME=
 DOCS=
 
-while getopts "hd:m:u:" OPTION
+while getopts "hd:m:i:p:u:" OPTION
 do
   case $OPTION in
     h)
@@ -47,6 +50,12 @@ do
       ;;
     m)
       MIRROR=${OPTARG}
+      ;;
+    i)
+      IMAGE_NAME=${OPTARG}
+      ;;
+    p)
+      NAME=${OPTARG}
       ;;
     u)
       DOCS=${OPTARG}
@@ -77,6 +86,18 @@ if [[ -z ${MIRROR} ]]; then
   echo "Error: missing mirror (-m) value"
   exit 1
 fi
+
+if [[ -z ${IMAGE_NAME} ]]; then
+  echo "Error: missing image name (-i) value"
+  exit 1
+fi
+
+if [[ -z ${NAME} ]]; then
+  echo "Error: missing proper name (-p) value"
+  exit 1
+fi
+
+TARGET="${IMAGE_NAME}-${BUILD_DATE}.tar.gz"
 
 if [[ -z ${DOCS} ]]; then
   DOCS="https://docs.joyent.com/images/lx-brand-beta"
