Add flag for specifying release

diff --git a/install b/install
--- a/install
+++ b/install
@@ -14,14 +14,15 @@ BUILD_DATE=$(date +%Y%m%d)
 usage() {
 cat <<EOF
 
-  Usage: $0 -d <chroot> -m <mirror> -i <image name> -p <proper name> -u <image docs>
+  Usage: $0 -r <RELEASE> -d <INSTALL_DIR> -m <MIRROR> -i <IMAGE_NAME> -p <NAME> -u <DOCS>
   
   Install and modify Debian in a given directory in a given directory using a given mirror
 
   Example:
-  $0 -d /data/chroot -m http://httpredir.debian.org/debian/ -i lx-debian-7 -p "Debian 7 LX Brand" -u https://docs.joyent.com/images/lx-brand-beta
+  $0 -r wheezy -d /data/chroot -m http://httpredir.debian.org/debian/ -i lx-debian-7 -p "Debian 7 LX Brand" -u https://docs.joyent.com/images/lx-brand-beta
 
   OPTIONS:
+  -r The desired release (e.g "wheezy")
   -d A path to the install directory
   -m A URL for the desired archive mirror
   -i The name of the image. This is used for naming the tarball. 
@@ -38,12 +39,15 @@ IMAGE_NAME=
 NAME=
 DOCS=
 
-while getopts "hd:m:i:p:u:" OPTION
+while getopts "hr:d:m:i:p:u:" OPTION
 do
   case $OPTION in
     h)
       usage
       exit
+      ;;
+    r)
+      RELEASE=${OPTARG}
       ;;
     d)
       INSTALL_DIR=${OPTARG%/}
@@ -69,6 +73,11 @@ done
 
 if [[ $# -eq 0 ]]; then
   usage
+  exit 1
+fi
+
+if [[ -z ${RELEASE} ]]; then
+  echo "Error: missing release (-r) value"
   exit 1
 fi
 
@@ -111,7 +120,7 @@ if [[ -d $INSTALL_DIR ]]; then
   mkdir -p $INSTALL_DIR
 fi
 
-debootstrap wheezy $INSTALL_DIR $MIRROR
+debootstrap $RELEASE $INSTALL_DIR $MIRROR
 echo "==> Done!"
 
 echo "==> Settting locale to en_US.UTF-8"
