Don't hardcode install path or archive mirror
Also added usage

diff --git a/install b/install
--- a/install
+++ b/install
@@ -8,14 +8,63 @@
 set -euo pipefail
 IFS=$'\n\t'
 
-INSTALL_DIR=/data/chroot
-MIRROR=http://httpredir.debian.org/debian/
 NAME="Debian 7 LX Brand"
 BUILD_DATE=$(date +%Y%m%d)
 DOCS="https://docs.joyent.com/images/lx-brand-beta"
 TARGET="debian-7-lx-${BUILD_DATE}.tar.gz"
 
-echo "==> Installing Debian 7 into $INSTALL_DIR"
+usage() {
+cat <<EOF
+
+  Usage: $0 -d <chroot> -m <mirror>
+  
+  Install and modify Debian in a given directory in a given directory using a given mirror
+
+  Example:
+  $0 -d /data/chroot -m http://httpredir.debian.org/debian/
+
+  OPTIONS:
+  -d A path to the install directory
+  -m A URL for the desired archive mirror
+  -h Show this message
+
+EOF
+}
+
+INSTALL_DIR=
+MIRROR=
+
+while getopts "hd:m:" OPTION
+do
+  case $OPTION in
+    h)
+      usage
+      exit
+      ;;
+    d)
+      INSTALL_DIR=${OPTARG%/}
+      ;;
+    m)
+      MIRROR=${OPTARG}
+      ;;
+    ?)
+      usage
+      exit
+      ;;
+  esac
+done
+
+if [[ $# -eq 0 ]]; then
+  usage
+  exit 1
+fi
+
+if [[ ! -e "$INSTALL_DIR" ]] ; then
+  echo "Directory $INSTALL_DIR not found"
+  exit 1
+fi
+
+echo "==> Installing Debian into $INSTALL_DIR"
 
 if [ -d $INSTALL_DIR ]; then
   echo "====> Found previous chroot. Deleting and creating a new one."
